import type { Metadata } from "next";
import "../globals.css";
import Footer from "../components/sections/footer";
import Navigation from "../components/sections/navigation";
import CommandPalette from "../components/headlessUiComponents/modal";
import AppLayoutAuth from ".";
import { ProductModal } from "../components/utils/product-details";



export const metadata: Metadata = {
  title: "Beegee Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppLayoutAuth>
          <Navigation/>
          {children}
          <Footer/>
          <CommandPalette/>
          <ProductModal />
        </AppLayoutAuth>
      </body>
      
    </html>
  );
}
